const express = require('express');

const app = express();
app.set('trust proxy', 1);
app.use(express.json());

require('./handlers/misc/getStatus')(app);
require('./handlers/users/authorizeUser')(app);
require('./handlers/users/changePassword')(app);
require('./handlers/users/createUser')(app);
require('./handlers/users/forgotPassword')(app);
require('./handlers/users/getUser')(app);
require('./handlers/users/resetPassword')(app);
require('./handlers/users/updateUser')(app);
require('./handlers/users/validateToken')(app);
require('./handlers/users/verifyUser')(app);
require('./handlers/users/socialLogin')(app);
require('./handlers/users/getUserActivity')(app);
require('./handlers/polls/createPoll')(app);
require('./handlers/polls/updatePoll')(app);
require('./handlers/polls/getPoll')(app);
require('./handlers/polls/getPolls')(app);
require('./handlers/polls/deletePoll')(app);
require('./handlers/polls/votePoll')(app);
require('./handlers/polls/getVotes')(app);
require('./handlers/articles/createArticle')(app);
require('./handlers/articles/updateArticle')(app);
require('./handlers/articles/deleteArticle')(app);
require('./handlers/pages/createPage')(app);
require('./handlers/pages/updatePage')(app);
require('./handlers/pages/getPage')(app);
require('./handlers/pages/deletePage')(app);
require('./handlers/blogs/createBlog')(app);
require('./handlers/blogs/updateBlog')(app);
require('./handlers/blogs/deleteBlog')(app);
require('./handlers/items/shareItem')(app);
require('./handlers/items/getItems')(app);
require('./handlers/items/updateContent')(app);
require('./handlers/items/tags')(app);
require('./handlers/items/snippets')(app);
require('./handlers/items/getStreamPictures')(app);
require('./handlers/misc/imageUpload')(app);
require('./handlers/misc/tagList')(app);
require('./handlers/comments/createComment')(app);
require('./handlers/comments/getComments')(app);
require('./handlers/comments/voteComment')(app);
require('./handlers/comments/getVotes')(app);
require('./handlers/misc/getTwitterEmbed')(app);

module.exports = app;
